Problem description --> System.Exception: Something went wrong
   at Await.Program.<Test_AsyncInCatchFinally>d__1.MoveNext() in C:\Users\Prestige-Mac\Dropbox\PackTPub\Exercises\Section 4\Section 4.9\Finish\ExpertDotNet\Await\Program.cs:line 39
Logging complete. 
